### ISSUE TITLE
iCub HeadEdge – Neck Variant 1: Tendonless Serial Mechanism – Final Rush

### ISSUE THREAD

**Issue by Nicogene** [icub-tech-iit/study-icub-headedge#147]
This is the todo list to ultimate the serial neck project:

- [x] Make the yaw wave generator (HD) possible to assemble, with a tool and proper holes
- [x] Bring all the magnet-to-AEA3 sensor distances to 0.8 mm
- [x] Fix the inner motor supports hole value and tolerance
- [x] Remaining drawings (from green split included upwards)
  - [x] #151
- [x] #150
- [x] #155
- [x] Repair and restructure all the assemblies to respect the mounting sequence (#157)
- [x] Verify all the movements in their RoM against possible clashes (#157)
- [x] Create two different neck assemblies for iCub and ergoCub (#157)
- [x] #171 

cc @Lawproto @pattacini
