### ISSUE TITLE
iCubHeadEdge – Neck mk3 assembly housekeeping

### ISSUE THREAD

**Issue by Nicogene** [icub-tech-iit/study-icub-headedge#157]
### Task description
We would like to:
- [x] Repair and restructure all the assemblies to respect the mounting sequence
- [x] Verify all the movements in their RoM against possible clashes
- [x] Create two different neck assemblies for iCub and ergoCub

### Definition of done

The above list has been completed
