### ISSUE TITLE
iCub HeadEdge – Detailed mech design of the serial variant - Stint 2

### ISSUE THREAD

**Issue by Nicogene** [icub-tech-iit/study-icub-headedge#78]
### Task description

This is the follow-up of:
- #63

We would like to finalize the design of the pitch:
- [x] Accommodate the AEA3 on the pitch joint.
- [x] Check the qualitative stress for the two main columns.
- [x] Check the load for these dowel pins.

### Definition of done
All points are ticked in.
