### ISSUE TITLE
iCub HeadEdge – Detailed mech design of the serial variant - Stint 3

### ISSUE THREAD

**Issue by Nicogene** [icub-tech-iit/study-icub-headedge#89]
### Task description

This is the follow-up of:
- #78 

We would like to:
- [x] Protect the Harmonic Drive from dust and dirt from the flexible spline side too.
- [x] Guarantee the centering of the flexible spline while assembling
- [ ] Split the first rotating piece (blue) into assemblable parts

### Definition of done

The above list is completed
