### ISSUE TITLE
iCub HeadEdge – Detailed mech design of the serial variant - Stint X

### ISSUE THREAD

**Issue by Nicogene** [icub-tech-iit/study-icub-headedge#90]
### Task description

After the F2F meeting w/ Diego Torazza, it came out that we could implement the following improvements:

- [ ] Add one more bearing over the custom green shaft, so that centering between the pink cap and the wave generator is more accurate.
- [x] Extend the pink piece so that it becomes a support for the motor and dump the magenta piece out, so that the centering between the pink cap and the motor is more accurate.
- [x] Make the holes for the circular spline with clearance for the yellow piece and threaded for the pink piece, so that we can avoid having to screw the pink over the yellow.

### Definition of done

The above list is completed
